### PR TITLE
switch to Bullseye

### PR DESCRIPTION
**Pull request by adamralph**
I'm deprecating simple-targets-csx in favour of [Bullseye](https://github.com/adamralph/bullseye) (it's a regular binary package instead of scripts, so can optionally be used in a [regular .NET project](https://github.com/xbehave/xbehave.net/blob/6d798877b4b891ce95ea8f2c5f9bee3d56a26bae/targets/Program.cs#L8)).

### CODE REVIEW

**Comment by adamralph** [comment]
I think the build is failing for an unrelated reason.

**Comment by pauldotknopf** [comment]
Wait, are you using this project? Or are you just being polite?

**Comment by pauldotknopf** [comment]
I need to migrate this project away from `dotnet-script`. I've followed your advice and am just doing a simple `dotnet run` with a `Program.cs`.

https://github.com/pauldotknopf/gitlab-page-server/blob/develop/build/scripts/Program.cs

Each of the build projects share code via submodule: https://github.com/pauldotknopf/dotnet-buildary/tree/master

Thanks again!

**Comment by adamralph** [comment]
You're welcome. 😃 

> Wait, are you using this project? Or are you just being polite?

I have to admit that I'm not using the project. The reason for this PR is two-fold: a) to help people switch away from simple-targets-csx which I am going to archive (the "being polite" part :wink:) and b) to ensure that Bullseye doesn't regress from simple-targets-csx in any way.

The buildary stuff looks interesting!

**Pull request merged**
